# Generated by Django 3.1.1 on 2020-10-11 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rescue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(max_length=30)),
                ('rescuer_name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=40)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('contact_no', models.CharField(max_length=11)),
                ('animal_photo', models.ImageField(upload_to='forms/rescue/')),
                ('closed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_id', models.PositiveIntegerField()),
                ('adopter_name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=40)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('contact_no', models.CharField(max_length=11)),
                ('adopter_photo', models.ImageField(upload_to='forms/adoption/')),
                ('closed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
